blank_issues_enabled: false
contact_links:
    - name: ❗️ All other issues
      url: https://github.com/privateaim/hub-seeder/discussions
      about: |
          Please use GitHub Discussions for other issues and asking questions.
